FROM python:3.12-slim

WORKDIR /app

RUN python -m pip install --upgrade pip \
    && python -m pip install --no-cache-dir duckdb==1.5.4 kaggle==2.2.2

COPY scripts /app/scripts

ENV PYTHONPATH="/app/scripts"
